# Generated by Django 3.0.8 on 2020-09-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200906_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(default='Enter The Description', max_length=2048),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
